# -*- coding: utf-8 -*-
"""ReverseArray.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cV9BKsNh84wCrdYsRAPEffzNsxi2vMUZ
"""

def reverse(n):
  start=0
  end=len(n)
  while start>end:
    n[start],n[end]=n[end],n[start]
    start+=1
    end-=1
  return n
n=list(map(int,input().split()))
print(reverse(n))